# Use root/example as user/password credentials
version: '3.8'
#services:
#  db:
#    image: mysql:8.0
#    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
#    # (this is just an example, not intended to be a production configuration)
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: example
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080

services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      #      - MYSQL_DATABASE=quotes
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    ports:
      - '3306:3306'
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
#    volumes:
#      - db:/var/lib/mysql
#      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
#volumes:
#  db:
#    driver: local

#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U postgres -d master"]
#      interval: 10s
#      timeout: 5s
#      retries: 3
