server:
  port: 8080
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        default_schema: public
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        default_schema: master
    hibernate:
      ddl-auto: none
    open-in-view: false
multitenancy:
  master:
#    database: master
#    datasource:
#      url: jdbc:postgresql://localhost:5432/master
#      username: postgres
#      password: secret
#      hikari:
#        maximum-pool-size: 1
    datasource:
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://localhost:3306/master
      username: root
      password: mauFJcuf5dhRMQrjj
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        poolName: Hikari
        data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
        minimum-idle: 10
        maximum-pool-size: 30
        connection-timeout: 60000
    repository:
      packages: se.callista.blog.service.multitenancy.repository
    entityManager:
      packages: se.callista.blog.service.multitenancy.domain
    liquibase:
      enabled: false
  shard:
    username: app_user
    password: secret
    datasource:
#      url-prefix: jdbc:postgresql://localhost:5432/
      url-prefix: jdbc:mysql://localhost:3306/
    liquibase:
      enabled: true
      changeLog: classpath:db/changelog/db.changelog-shard.yaml
      parameters:
        schema: ${spring.jpa.properties.hibernate.default_schema}
        database: ${multitenancy.master.database}
        app_db_user: ${multitenancy.shard.username}
        app_db_password: ${multitenancy.shard.password}
  tenant:
    repository:
      packages: se.callista.blog.service.repository
    entityManager:
      packages: se.callista.blog.service.domain

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE