server:
  port: 8088
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        default_schema: master
    open-in-view: false

multitenancy:
  master:
    datasource:
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://localhost:3306/master
      username: root
      password: mauFJcuf5dhRMQrjj
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        poolName: Hikari
        data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
        minimum-idle: 10
        maximum-pool-size: 30
        connection-timeout: 60000
    liquibase:
      changeLog: classpath:db/changelog/db.changelog-master.yaml
  shard:
    max-tenants: 2
    datasource:
      url-prefix: jdbc:mysql://localhost:3306/
    liquibase:
      enabled: true
      changeLog: classpath:db/changelog/db.changelog-shard.yaml
      parameters:
        schema: master
        app_db_user: app_user
        app_db_password: secret

#logging:
#    level:
#        org.hibernate.SQL: DEBUG
#        org.hibernate.type: TRACE
